version: '3.8'

services:
  task_manager_postgres:
    image: postgres:14-alpine
    container_name: task_manager_postgres
    hostname: task_manager_postgres
    restart: always
    ports:
      - 
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
    networks:
      - task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

  task_manager_bot: 
    container_name: task_manager_bot
    hostname: task_manager_bot
    restart: always
    ports:
      - 
    build:
      context: "./bot"
    networks:
      - task_manager
    depends_on:
      - task_manager_postgres

networks:
  task_manager:
    driver: bridge

volumes:
  postgres_data: {} 
